<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Libreria.LogicaAplicacion</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Obligatorio.Infraestructura\Obligatorio.Infraestructura.csproj" />
    <ProjectReference Include="..\Obligatorio.LogicaNegocio\Obligatorio.LogicaNegocio.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="CasosUso\" />
    <Folder Include="Dtos\" />
  </ItemGroup>

</Project>
